### PR TITLE
Feature/gefs v12 port2acorn

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
WCOSS2 Transition for GEFSv12

### CODE REVIEW

**Comment by XianwuXue-NOAA** [comment]
@SamuelTrahanNOAA @WalterKolczynski-NOAA Could you review my changes? Thanks a lot in advance.

**Review by SamuelTrahanNOAA — APPROVED** [review]
Beatific changes.

**Comment by XianwuXue-NOAA** [comment]
Thanks @SamuelTrahanNOAA

**Comment by XianwuXue-NOAA** [comment]
@SamuelTrahanNOAA Could you create a tag as "gefs_v12.2.0" for this release/gefs_v12? Thanks.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA Could you create a tag as "gefs_v12.2.0" for this release/gefs_v12? Thanks.

There is now an annotated tag "gefs_v12.2.0" with the commit comment "WCOSS2 Transition for GEFSv12"

**Comment by XianwuXue-NOAA** [comment]
Thanks again @SamuelTrahanNOAA

**Pull request merged**
